[platformio]
src_dir = .
include_dir = include

[env:nano_new]
platform = atmelavr
framework = arduino
board = nanoatmega328new
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    adafruit/Adafruit BusIO
    evert-arias/EasyButton

[env:nano_old]
platform = atmelavr
framework = arduino
board = nanoatmega328
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    adafruit/Adafruit BusIO
    evert-arias/EasyButton